# -*- coding: utf-8 -*-
"""Categoricalfeatureengineering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BrDoTyzG-4sTP4fmfT1P-ctM7ZJhVwle
"""

import pandas as pd
import numpy as np

df=pd.read_csv('vgsales.csv',encoding='utf-8')
df[['Name','Platform','Year','Genre','Publisher']].iloc[1:3]

gen=np.unique(df['Genre'])
gen

from sklearn.preprocessing import LabelEncoder

gle=LabelEncoder()
g_labels=gle.fit_transform(df['Genre'])
g_mapping={index: label for index, label in enumerate(gle.classes_)}
g_mapping

