# -*- coding: utf-8 -*-
"""featureengineering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s5-zXmXSpt1asoGHTj2jFYKncYwC-YSz
"""

filename='pima-indians-diabetes.data.csv'
names=['pneg' , 'plas','pres','skin','test','mass','pedi','age','class']

import pandas as pd

df=pd.read_csv(filename,names=names)

df

data=df.values

x=data[:,0:8]
y=data[:,8]

x

y

#scaling

df.head()

from sklearn.preprocessing import MinMaxScaler

mmscaler=MinMaxScaler(feature_range=(0,1))

reScalex=mmscaler.fit_transform(x)

reScalex

#standadarization of data

x

x[:,0].mean()

x[:,0].std()

#it is not a Gaussian distribution as mean is not 0 and deviation is not 1 so we can convert it into Gaussian Distribution

from sklearn.preprocessing import StandardScaler

ssScaler=StandardScaler()

rescalex=ssScaler.fit_transform(x)

rescalex

x

from sklearn.preprocessing import RobustScaler

rscaler=RobustScaler()

rescalex=rscaler.fit_transform(x)

rescalex

#standardisation affects cols
#normalisation effect rows

from sklearn.preprocessing import Normalizer

norm=Normalizer()

norm.fit_transform(x)
#useful when dealing with Euclidean distance calculation

