# -*- coding: utf-8 -*-
"""Week0_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NLPkpSMb-aXsjitOVkIxtkEy2w33e8tp
"""

from google.colab import drive
drive.mount('/content/drive')

fhand=open("/DAAassign.txt","r")
print(fhand.read())

import pandas as pd
url= "https://tinyurl.com/simulated-excel"
data=pd.read_excel(url,sheet_name=0,header=1)
data.head(2)

import pandas as pd
url="https://tinyurl.com/simulated-json"
dataframe=pd.read_json(url,orient='columns')
dataframe

import pandas as pd 
iris = pd.read_csv('/content/drive/My Drive/English/iris.cvs')
iris