# -*- coding: utf-8 -*-
"""week_3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ilV688vXrw8b5GsOaP8vMLkBABMEizZ

#Data Transformation and data scaling
"""

filename='/content/drive/MyDrive/Colab Notebooks/pima-indians-diabetes.data.csv'
names=['preg','plas','pres','skin','test','mass','pedi','age','class']

import pandas as pd

df=pd.read_csv(filename,names=names)

data=df.values

data

x=data[:,0:8]
y=data[:,8]

x

y

from sklearn.preprocessing import MinMaxScaler

mmScaler=MinMaxScaler(feature_range=(0,1))

rescaleX=mmScaler.fit_transform(x)

rescaleX

x[:,0].mean()

x[:,0].std()

from sklearn.preprocessing import StandardScaler

sScaler=StandardScaler()

rescaleX=sScaler.fit_transform(x)

rescaleX

rescaleX[:,0].mean()

rescaleX[:,0].std()

"""###Standardization affects columns
###Normalization affects rows
"""

from sklearn.preprocessing import Normalizer

norm=Normalizer()

norm.fit_transform(x)

