# -*- coding: utf-8 -*-
"""Week_1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRgwGOexcAKgoNhBZSYIJJ7NhMBO-SVu
"""

import sklearn

from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

dataset=datasets.load_iris()

#fit a cart model to the data
model=DecisionTreeClassifier()
model.fit(dataset.data,dataset.target)
print(model)

#make predictions
expected=dataset.target
predicted=model.predict(dataset.data)

#summarize the fit of the model
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

dataset

print(len(dataset.data))

import pandas as pd
data=pd.DataFrame(dataset.data)

data

data.size

data.info

data.describe

data.shape

#using Seaborn
import seaborn as sns

sns.set_theme()

#Example 1 dataset
tips=sns.load_dataset("tips")

sns.relplot(
    data=tips,
    x="total_bill" , y="tip" , col="time",
    hue="smoker" , style="smoker"  , size="size",
)

#Example 2 dataset
dots=sns.load_dataset("dots")
print(dots)

sns.relplot(
    data=dots , kind="line" , 
    x="time" ,  y="firing_rate" ,col="align" , 
    hue="choice" , size="coherence" , style="choice" , facet_kws=dict(sharex=False),
)

sns.relplot(
    data=dots , kind="line" , 
    x="time" ,  y="firing_rate" ,col="align" , 
    hue="choice" , size="coherence" , style="choice" , facet_kws=dict(sharex=True),
)

sns.relplot(
    data=dots , kind="line" , 
    x="time" ,  y="firing_rate" ,
)

sns.relplot(
    data=dots , kind="line" , 
    x="time" ,  y="firing_rate" ,col="choice" , 
    
)

sns.relplot(
    data=dots , kind="line" , 
    x="time" ,  y="firing_rate" ,col="coherence" , 
    
)

sns.relplot(
    data=dots , kind="line" , 
    x="time" ,  y="firing_rate" ,col="choice" , 
    hue="coherence"
)

#Example 3 dataset
iris=sns.load_dataset("iris")
print(iris)

sns.relplot(
    data=iris , 
    x="sepal_length" , y="sepal_width" , col="species" , kind="line" ,
)

penguin=sns.load_dataset("penguins")
print(penguin)

sns.pairplot(data=penguin,hue="species")